<?php

namespace AndroidDev\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleProjetRepository extends EntityRepository
{

    public function findPartByProjetAndArticle($projet, $article)
    {

        $query = $this->_em->createQuery('SELECT ap FROM AndroidDevSiteBundle:ArticleProjet ap WHERE ap.Projet = :projet AND ap.Article = :article');
        $query->setParameter('projet', $projet);
        $query->setParameter('article', $article);
        return $query->getOneOrNullResult();
    }

}
