<?php

namespace AndroidDev\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function findLastArticleByPage($page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at WHERE a.visible = 1 AND (at.id = 1 OR at.id = 2) AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        return $query->getResult();
    }

    public function findArticleByPage($page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at WHERE a.visible = 1 AND at.id = 1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        return $query->getResult();
    }

    public function findArticleCatByPage($slug, $page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at JOIN a.Categorie ac WHERE a.visible = 1 AND at.id = 1 AND ac.slug = :slug AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('slug', $slug);
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        return $query->getResult();
    }

    public function findArticleCatByIdCat($id, $nb)
    {
        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at JOIN a.Categorie ac WHERE a.visible = 1 AND at.id = 1 AND ac.id = :id AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('id', $id);
        $query->setMaxResults($nb);
        return $query->getResult();
    }

    public function findArticleCatByIdKey($id, $nb)
    {
        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at JOIN a.MotCles am WHERE a.visible = 1 AND at.id = 1 AND am.id = :id AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('id', $id);
        $query->setMaxResults($nb);
        return $query->getResult();
    }

    public function findAstuceByPage($page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at WHERE a.visible = 1 AND at.id = 2 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        return $query->getResult();
    }

    public function findAstuceCatByPage($slug, $page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at JOIN a.Categorie ac WHERE a.visible = 1 AND at.id = 2 AND ac.slug = :slug AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('slug', $slug);
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        return $query->getResult();
    }

    public function findProjetByPage($page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $query = $this->_em->createQuery('SELECT p FROM AndroidDevSiteBundle:Projet p WHERE p.visible = 1 ORDER BY p.created DESC');
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        return $query->getResult();
    }

    public function findBySlug($slug)
    {
        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a WHERE a.slug = :slug AND a.visible=1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP())');
        $query->setParameter('slug', $slug);
        return $query->getOneOrNullResult();
    }

    public function findByMotCles($slug, $page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.MotCles am WHERE am.slug = :slug AND a.visible=1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC ');
        $query->setParameter('slug', $slug);
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        return $query->getResult();
    }

    public function findById($id)
    {
        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a WHERE a.id = :id AND a.visible=1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP())');
        $query->setParameter('id', $id);
        return $query->getOneOrNullResult();
    }

    public function findByTop()
    {
        $query = $this->_em->createQuery('SELECT count(a) FROM AndroidDevSiteBundle:Article a WHERE a.top = 1 AND a.visible=1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP())');
        $count = $query->getSingleScalarResult();

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a WHERE a.top = 1 AND a.visible=1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP())');
        $query->setFirstResult(rand(0, $count - 1));
        $query->setMaxResults(1);
        return $query->getOneOrNullResult();
    }

    public function findByNom($nom)
    {
        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a WHERE a.titre = :titre AND a.visible=1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP())');
        $query->setParameter('titre', ltrim($nom));
        return $query->getOneOrNullResult();
    }

    public function findLastUpdateArticle($nb)
    {
        $query = $this->_em->createQuery('SELECT a 
            FROM AndroidDevSiteBundle:Article a 
            JOIN a.Type t
            WHERE (t.id = 1 OR t.id = 2) AND a.visible = 1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) AND a.updated > a.created
            ORDER BY a.updated DESC');
        $query->setMaxResults($nb);
        return $query->getResult();
    }

    public function findAllPartProject()
    {

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type t WHERE t.id = 3 AND a.visible = 1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        return $query->getResult();
    }

    public function getArticleBySearch($motCles, $page, $nb)
    {
        $deb = ($nb * $page) - ($nb);

        $requete = 'SELECT a FROM AndroidDevSiteBundle:Article a
                        JOIN a.Type at
                        WHERE a.visible = 1 AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP())';

        foreach ($motCles as $cle => $motCle) {
            $requete .=" AND ( a.titre LIKE '%" . $motCle . "%' OR a.sousTitre LIKE '%" . $motCle . "%' OR a.contenu LIKE '%" . $motCle . "%' ) ";
        }
        $requete .=" ORDER BY a.created DESC ";

        $query = $this->_em->createQuery($requete);
        $query->setMaxResults($nb);
        $query->setFirstResult($deb);
        $articles = $query->getResult();

        return $articles;
    }

    /**
     * retourne les articles liés pour un article
     * @param \AndroidDev\SiteBundle\Entity\Article $article 
     * @param int $max
     * @return type
     */
    public function findLink($article, $max)
    {
        $idMotCle = [];
        $listeArticles = [];
        $listeArticlesId = [];

        foreach ($article->getMotCles() as $motcle) {
            $idMotCle[] = $motcle->getId();
        }

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.MotCles am WHERE a.visible = 1 AND am.id IN (:motcles) AND a.id != :id  AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('motcles', $idMotCle);
        $query->setParameter('id', $article->getId());
        $query->setMaxResults(6);
        $listeArticles = array_merge($listeArticles, $query->getResult());

        $listeArticlesId = [$article->getId()];
        foreach ($listeArticles as $articleliste) {
            $listeArticlesId[] = $articleliste->getId();
        }

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Type at WHERE a.visible = 1 AND at.id = :type AND a.id NOT IN (:id)  AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('type', $article->getType()->getId());
        $query->setParameter('id', $listeArticlesId);
        $query->setMaxResults(2);
        $listeArticles = array_merge($listeArticles, $query->getResult());

        $listeArticlesId = [$article->getId()];
        foreach ($listeArticles as $articleliste) {
            $listeArticlesId[] = $articleliste->getId();
        }

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Categorie ac WHERE a.visible = 1 AND ac.id = :cat AND a.id NOT IN (:id)  AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('cat', $article->getCategorie()->getId());
        $query->setParameter('id', $listeArticlesId);
        $query->setMaxResults(2);
        $listeArticles = array_merge($listeArticles, $query->getResult());

        $listeArticlesId = [$article->getId()];
        foreach ($listeArticles as $articleliste) {
            $listeArticlesId[] = $articleliste->getId();
        }

        $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a JOIN a.Categorie ac WHERE a.visible = 1 AND ac.id = :cat AND a.id NOT IN (:id)  AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
        $query->setParameter('cat', $article->getCategorie()->getId());
        $query->setParameter('id', $listeArticlesId);
        $query->setMaxResults(2);
        $listeArticles = array_merge($listeArticles, $query->getResult());

        $listeArticlesId = [$article->getId()];
        foreach ($listeArticles as $articleliste) {
            $listeArticlesId[] = $articleliste->getId();
        }

        $nbArticleReste = $max - count($listeArticles);
        
        if ($nbArticleReste > 0) {
            $query = $this->_em->createQuery('SELECT a FROM AndroidDevSiteBundle:Article a WHERE a.visible = 1 AND a.id NOT IN (:id)  AND (a.publishedAt IS NULL OR a.publishedAt< CURRENT_TIMESTAMP()) ORDER BY a.created DESC');
            $query->setParameter('id', $listeArticlesId);
            $query->setMaxResults($nbArticleReste);
            $listeArticles = array_merge($listeArticles, $query->getResult());
        }

        return $listeArticles;
    }

}
