<?php

namespace AndroidDev\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoSiteRepository extends EntityRepository
{

    public function findByArray($i)
    {
        // On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
        $qb = $this->_em->createQueryBuilder();

        $qb->select('if')
                ->from('AndroidDevSiteBundle:InfoSite', 'if')
                ->where('if.id = :id')
                ->setParameter('id', $i);

        return $qb->getQuery()->getArrayResult();
        
    }

}
