<?php

namespace AndroidDev\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{

    public function findNotEmpty()
    {
        $query = $this->_em->createQuery('SELECT p FROM AndroidDevSiteBundle:Projet p 
                        INNER JOIN p.Articles pa
                        ORDER BY p.titre');
        $projets = $query->getResult();
        
        return $projets;
    }

}
