androiddev_accueil:
    pattern:   /{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:index, page: 1 }
    requirements:
        page:  \d*
 
androiddev_article:
    pattern:   /article/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:article, page: 1 }
    requirements:
        page:  \d*
    
androiddev_astuce:
    pattern:   /astuce/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:astuce, page: 1 }
    requirements:
        page:  \d*
 
androiddev_projet:
    pattern:   /projet/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:projet, page: 1 }
    requirements:
        page:  \d*
 
androiddev_voir:
    pattern:   /{slug}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:voir }