androiddev_accueil:
    pattern:   /{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:index, page: 1 }
    requirements:
        page:  \d*
 
androiddev_article:
    pattern:   /article/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:article, page: 1 }
    requirements:
        page:  \d*
    
androiddev_astuce:
    pattern:   /astuce/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:astuce, page: 1 }
    requirements:
        page:  \d*
 
androiddev_projet:
    pattern:   /projet/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:projet, page: 1 }
    requirements:
        page:  \d*
 
androiddev_articleCat:
    pattern:   /article/{slug}/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:articleCat, page: 1 }
    requirements:
        page:  \d*
    
androiddev_astuceCat:
    pattern:   /astuce/{slug}/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:astuceCat, page: 1 }
    requirements:
        page:  \d*
 
androiddev_voir:
    pattern:   /{slug}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:voir }
 
androiddev_search:
    pattern:   /recherche/
    defaults:  { _controller: AndroidDevSiteBundle:Blog:search }
 
androiddev_recherche:
    pattern:   /recherche/{motcles}/{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:recherche, page: 1 }
    requirements:
        page:  \d*
 
androiddev_projetVoir:
    pattern:   /projet/{slug}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:projetVoir }