androiddev_accueil:
    pattern:   /{page}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:index, page: 1 }
    requirements:
        page:  \d*
 
androiddev_voir:
    pattern:   /article/{id}
    defaults:  { _controller: AndroidDevSiteBundle:Blog:voir }
    requirements:
        id:  \d+