parameters:
#    android_dev_site.example.class: AndroidDev\SiteBundle\Example

services:
#    android_dev_site.example:
#        class: %android_dev_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
