parameters:
#    android_dev_admin.example.class: AndroidDev\AdminBundle\Example

services:
#    android_dev_admin.example:
#        class: %android_dev_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
