parameters:
#    android_dev_admin.example.class: AndroidDev\AdminBundle\Example

services:
    androiddev_user.registration.form.type:
        class: AndroidDev\AdminBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: androiddev_user_registration }