parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     android-dev
    database_user:     root
    database_password: Okirrchsim1

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~a

    locale:            fr
    secret:            6a40c410b1b7951d10bea7be812bb561f7