<?php

namespace AndroidDev\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
